---
title: "Swenson Appl. Stats Project"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---


```{r Base Data}
library(readxl)
Howells_Dataset_COPY <- read_excel("Howells Dataset COPY.xlsx")
View(Howells_Dataset_COPY)
Japan= Howells_Dataset_COPY

# NLB, ZYB, and ZMB are facial measurements
#GOL, XCB, & FRC, are cranial measurements

summary(Japan$GOL)
summary(Japan$XCB)
summary(Japan$FRC)
summary(Japan$NLB)
summary(Japan$ZYB)
summary(Japan$ZMB)

sd(Japan$GOL)
sd(Japan$XCB)
sd(Japan$FRC)
sd(Japan$NLB)
sd(Japan$ZYB)
sd(Japan$ZMB)

#female code is 1, male code is 2

#Cranial: GOL, XCB, FRC
GOLfemale=Japan$GOL[Japan$SexCode=="1"]
GOLmale=Japan$GOL[Japan$SexCode=="2"]

XCBfemale=Japan$XCB[Japan$SexCode=="1"]
XCBmale=Japan$XCB[Japan$SexCode=="2"]

FRCfemale=Japan$FRC[Japan$SexCode=="1"]
FRCmale=Japan$FRC[Japan$SexCode=="2"]

#Facial: NLB, ZYB, ZMB
NLBfemale=Japan$NLB[Japan$SexCode=="1"]
NLBmale=Japan$NLB[Japan$SexCode=="2"]

ZYBfemale=Japan$ZYB[Japan$SexCode=="1"]
ZYBmale=Japan$ZYB[Japan$SexCode=="2"]

ZMBfemale=Japan$ZMB[Japan$SexCode=="1"]
ZMBmale=Japan$ZMB[Japan$SexCode=="2"]

```


```{r Exploratory Data Analysis}
#EDA

par(mfrow=c(1,2))
hist(GOLfemale, main="GOL Histogram F",prob=T, col="red")
hist(GOLmale, main="GOL Histogram M",prob=T, col="red")
par(mfrow=c(1,2))
hist(XCBfemale, main="XCB Histogram F",prob=T, col="orange")
hist(XCBmale, main="XCB Histogram M",prob=T, col="orange")
par(mfrow=c(1,2))
hist(FRCfemale, main="FRC Histogram F",prob=T, col="yellow")
hist(FRCmale, main="FRC Histogram M",prob=T, col="yellow")
par(mfrow=c(1,2))
hist(NLBfemale, main="NLB Histogram F",prob=T, col="green")
hist(NLBmale, main="NLB Histogram M",prob=T, col="green")
par(mfrow=c(1,2))
hist(ZYBfemale, main="ZYB Histogram F",prob=T, col="blue")
hist(ZYBmale, main="ZYB Histogram M",prob=T, col="blue")
par(mfrow=c(1,2))
hist(ZMBfemale, main="ZMB Histogram F",prob=T, col="purple")
hist(ZMBmale, main="ZMB Histogram M",prob=T, col="purple")

par(mfrow=c(1,2))
boxplot(GOLfemale, main="GOL Boxplot F",prob=T, col="red")
boxplot(GOLmale, main="GOL Boxplot M",prob=T, col="red")
par(mfrow=c(1,2))
boxplot(XCBfemale, main="XCB Boxplot F",prob=T, col="orange")
boxplot(XCBmale, main="XCB Boxplot M",prob=T, col="orange")
par(mfrow=c(1,2))
boxplot(FRCfemale, main="FRC Boxplot F",prob=T, col="yellow")
boxplot(FRCmale, main="FRC Boxplot M",prob=T, col="yellow")
par(mfrow=c(1,2))
boxplot(NLBfemale, main="NLB Boxplot F",prob=T, col="green")
boxplot(NLBmale, main="NLB Boxplot M",prob=T, col="green")
par(mfrow=c(1,2))
boxplot(ZYBfemale, main="ZYB Boxplot F",prob=T, col="blue")
boxplot(ZYBmale, main="ZYB Boxplot M",prob=T, col="blue")

par(mfrow=c(1,2))
qqnorm(GOLfemale, main="GOL QQ Plot F", pch=1)
qqline(GOLfemale, main="GOL QQ Plot F", lwd=3, col="red")
qqnorm(GOLmale, main="GOL QQ Plot M", pch=1)
qqline(GOLmale, main="GOL QQ Plot M", lwd=3, col="red")
par(mfrow=c(1,2))
qqnorm(XCBfemale, main="XCB QQ Plot F", pch=1)
qqline(XCBfemale, main="XCB QQ Plot F", lwd=3, col="orange")
qqnorm(XCBmale, main="XCB QQ Plot M", pch=1)
qqline(XCBmale, main="XCB QQ Plot M", lwd=3, col="orange")
par(mfrow=c(1,2))
qqnorm(FRCfemale, main="FRC QQ Plot F", pch=1)
qqline(FRCfemale, main="FRC QQ Plot F", lwd=3, col="yellow")
qqnorm(FRCmale, main="FRC QQ Plot M", pch=1)
qqline(FRCmale, main="FRC QQ Plot M", lwd=3, col="yellow")
par(mfrow=c(1,2))
qqnorm(NLBfemale, main="NLB QQ Plot F", pch=1)
qqline(NLBfemale, main="NLB QQ Plot F", lwd=3, col="green")
qqnorm(NLBmale, main="NLB QQ Plot M", pch=1)
qqline(NLBmale, main="NLB QQ Plot M", lwd=3, col="green")
par(mfrow=c(1,2))
qqnorm(ZYBfemale, main="ZYB QQ Plot F", pch=1)
qqline(ZYBfemale, main="ZYB QQ Plot F", lwd=3, col="blue")
qqnorm(ZYBmale, main="ZYB QQ Plot M", pch=1)
qqline(ZYBmale, main="ZYB QQ Plot M", lwd=3, col="blue")
par(mfrow=c(1,2))
qqnorm(ZMBfemale, main="ZMB QQ Plot F", pch=1)
qqline(ZMBfemale, main="ZMB QQ Plot F", lwd=3, col="purple")
qqnorm(ZMBmale, main="ZMB QQ Plot M", pch=1)
qqline(ZMBmale, main="ZMB QQ Plot M", lwd=3, col="purple")


```


```{r}
#Correlation
library(Sleuth2)
library(corrplot)
library(car)
library(olsrr)

NumericalJapan=data.frame(Japan$GOL,Japan$XCB,Japan$FRC,Japan$NLB,Japan$ZYB,Japan$ZMB)
Japanpairwise= cor(NumericalJapan)
corrplot(Japanpairwise)
pairs(NumericalJapan)
summary(NumericalJapan)

```

```{r}
#Corr numerical
measurementsonly=c(Japan$GOL, Japan$XCB, Japan$FRC, Japan$NLB, Japan$ZYB, Japan$ZMB)
Numcorr= data.frame(Japan$GOL, Japan$XCB, Japan$FRC, Japan$NLB, Japan$ZYB, Japan$ZMB)
print(cor(Numcorr))

```


```{r}
#T Testing
t.test(GOLfemale, GOLmale)
t.test(XCBfemale, XCBmale)
t.test(FRCfemale, FRCmale)
t.test(NLBfemale, NLBmale)
t.test(ZYBfemale, ZYBmale)
t.test(ZMBfemale, ZMBmale)

```


```{r}
logGOL=log(Japan$GOL)
logXCB=log(Japan$XCB)
logFRC=log(Japan$FRC)
logNLB=log(Japan$NLB)
logZYB=log(Japan$ZYB)
logZMB=log(Japan$ZMB)

sqrtGOL=sqrt(Japan$GOL)
sqrtXCB=sqrt(Japan$XCB)
sqrtFRC=sqrt(Japan$FRC)
sqrtNLB=sqrt(Japan$NLB)
sqrtZYB=sqrt(Japan$ZYB)
sqrtZMB=sqrt(Japan$ZMB)

recipGOL=1/Japan$GOL
recipXCB=1/Japan$XCB
recipFRC=1/Japan$FRC
recipNLB=1/Japan$NLB
recipZYB=1/Japan$ZYB
recipZMB=1/Japan$ZMB

```

```{r}
#Log Transformation
par(mfrow=c(1,3))
boxplot(logGOL, main="GOL Boxplot Log",prob=T, col="red")
boxplot(logXCB, main="XCB Boxplot Log",prob=T, col="orange")
boxplot(logFRC, main="FRC Boxplot Log",prob=T, col="yellow")
par(mfrow=c(1,3))
boxplot(logNLB, main="NLB Boxplot Log",prob=T, col="green")
boxplot(logZYB, main="ZYB Boxplot Log",prob=T, col="blue")
boxplot(logZMB, main="ZMB Boxplot Log",prob=T, col="purple")

par(mfrow=c(1,3))
qqnorm(logGOL, main="GOL QQ Plot Log", pch=1)
qqline(logGOL, main="GOL QQ Plot Log", lwd=3, col="red")
qqnorm(logXCB, main="XCB QQ Plot Log", pch=1)
qqline(logXCB, main="XCB QQ Plot Log", lwd=3, col="orange")
qqnorm(logFRC, main="FRC QQ Plot Log", pch=1)
qqline(logFRC, main="FRC QQ Plot Log", lwd=3, col="yellow")
par(mfrow=c(1,3))
qqnorm(logNLB, main="NLB QQ Plot Log", pch=1)
qqline(logNLB, main="NLB QQ Plot Log", lwd=3, col="green")
qqnorm(logZYB, main="ZYB QQ Plot Log", pch=1)
qqline(logZYB, main="ZYB QQ Plot Log", lwd=3, col="blue")
qqnorm(logZMB, main="ZMB QQ Plot Log", pch=1)
qqline(logZMB, main="ZMB QQ Plot Log", lwd=3, col="purple")

```

```{r}
#Sqrt Transformation
par(mfrow=c(1,3))
boxplot(sqrtGOL, main="GOL Boxplot sqrt",prob=T, col="red")
boxplot(sqrtXCB, main="XCB Boxplot sqrt",prob=T, col="orange")
boxplot(sqrtFRC, main="FRC Boxplot sqrt",prob=T, col="yellow")
par(mfrow=c(1,3))
boxplot(sqrtNLB, main="NLB Boxplot sqrt",prob=T, col="green")
boxplot(sqrtZYB, main="ZYB Boxplot sqrt",prob=T, col="blue")
boxplot(sqrtZMB, main="ZMB Boxplot sqrt",prob=T, col="purple")

par(mfrow=c(1,3))
qqnorm(sqrtGOL, main="GOL QQ Plot sqrt", pch=1)
qqline(sqrtGOL, main="GOL QQ Plot sqrt", lwd=3, col="red")
qqnorm(sqrtXCB, main="XCB QQ Plot sqrt", pch=1)
qqline(sqrtXCB, main="XCB QQ Plot sqrt", lwd=3, col="orange")
qqnorm(sqrtFRC, main="FRC QQ Plot sqrt", pch=1)
qqline(sqrtFRC, main="FRC QQ Plot sqrt", lwd=3, col="yellow")
par(mfrow=c(1,3))
qqnorm(sqrtNLB, main="NLB QQ Plot sqrt", pch=1)
qqline(sqrtNLB, main="NLB QQ Plot sqrt", lwd=3, col="green")
qqnorm(sqrtZYB, main="ZYB QQ Plot sqrt", pch=1)
qqline(sqrtZYB, main="ZYB QQ Plot sqrt", lwd=3, col="blue")
qqnorm(sqrtZMB, main="ZMB QQ Plot sqrt", pch=1)
qqline(sqrtZMB, main="ZMB QQ Plot sqrt", lwd=3, col="purple")
```

```{r}
#Reciprocal Transformation
par(mfrow=c(1,3))
boxplot(recipGOL, main="GOL Boxplot Recip",prob=T, col="red")
boxplot(recipXCB, main="XCB Boxplot Recip",prob=T, col="orange")
boxplot(recipFRC, main="FRC Boxplot Recip",prob=T, col="yellow")
par(mfrow=c(1,3))
boxplot(recipNLB, main="NLB Boxplot Recip",prob=T, col="green")
boxplot(recipZYB, main="ZYB Boxplot Recip",prob=T, col="blue")
boxplot(recipZMB, main="ZMB Boxplot Recip",prob=T, col="purple")

par(mfrow=c(1,3))
qqnorm(recipGOL, main="GOL QQ Plot Recip", pch=1)
qqline(recipGOL, main="GOL QQ Plot Recip", lwd=3, col="red")
qqnorm(recipXCB, main="XCB QQ Plot Recip", pch=1)
qqline(recipXCB, main="XCB QQ Plot Recip", lwd=3, col="orange")
qqnorm(recipFRC, main="FRC QQ Plot Recip", pch=1)
qqline(recipFRC, main="FRC QQ Plot Recip", lwd=3, col="yellow")
par(mfrow=c(1,3))
qqnorm(recipNLB, main="NLB QQ Plot Recip", pch=1)
qqline(recipNLB, main="NLB QQ Plot Recip", lwd=3, col="green")
qqnorm(recipZYB, main="ZYB QQ Plot Recip", pch=1)
qqline(recipZYB, main="ZYB QQ Plot Recip", lwd=3, col="blue")
qqnorm(recipZMB, main="ZMB QQ Plot Recip", pch=1)
qqline(recipZMB, main="ZMB QQ Plot Recip", lwd=3, col="purple")
```

